name: Push-to-GCE

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Vite React App to GCE on push to main branch
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (version 18.x is the latest stable)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies and build the Vite React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Deploy build files to GCE server
      - name: Deploy to GCE server
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCE_SSH_KEY }} 
          REMOTE_HOST: ${{ secrets.GCE_HOST_IP }} 
          REMOTE_USER: ${{ secrets.GCE_USERNAME }} 
          TARGET: /var/www/html/ 
          SOURCE: ./dist

      # Step 5: Execute remote commands on the GCE instance
      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.GCE_HOST_IP }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            # sudo rm -rf /var/www/html/*
            # sudo mv /var/www/html/*
            sudo systemctl restart nginx
